[workspace]
members = [
]
[package]
name = "lmdb_rust"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2021"
autobins = false

[lib]
name = "lmdb_rust"
crate-type = ["lib", "cdylib"]

[dependencies]
libc = "0.2"

[dev-dependencies]
tempfile = "3.14.0"
